language: python
python:
  - "3.6"
  
# command to install dependencies
install: "pip install -r requirements.txt"

services:
  - mysql
addons:
  mariadb: '10.4'

before_script:
  - sudo mysql -e 'create database testdb;'

script:
  - nosetests

# require the branch name to be master (note for PRs this is the base branch name)
notifications:
  slack:
    if: branch = master