language: python
python:
  - "3.6"
  
addons:
  mariadb: '10.4'

before_install:
  - sudo mysql -e 'create database testdb;'

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  global:
  - DATABASE_URI='mysql+pymysql://root:@localhost:3306/testdb'
  
script:
  - nosetests

# require the branch name to be master (note for PRs this is the base branch name)
notifications:
  slack:
    if: branch = master