services:
 - docker

language: python
python:
 - "3.6"

before_install:
 - docker pull couchdb:latest
 - docker run -d --name couchdb -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pass
   couchdb:latest
 - docker ps -a

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
 - curl -X GET http://localhost:5984/
 - curl -X PUT http://admin:pass@localhost:5984/test

script:
 - nosetests

after_success:
 - codecov

# require the branch name to be master (note for PRs this is the base branch name)
notifications:
 slack:
   if: branch = master
